version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: philos_video
      POSTGRES_USER: philos
      POSTGRES_PASSWORD: philos
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
