// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.14.0 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "CookieAuth.Scopes"
)

// Defines values for LiveStreamStatus.
const (
	Ended   LiveStreamStatus = "ended"
	Live    LiveStreamStatus = "live"
	Waiting LiveStreamStatus = "waiting"
)

// Defines values for PlaybackEventEventType.
const (
	Heartbeat         PlaybackEventEventType = "heartbeat"
	PlaybackEnd       PlaybackEventEventType = "playback_end"
	PlaybackError     PlaybackEventEventType = "playback_error"
	PlaybackStart     PlaybackEventEventType = "playback_start"
	QualityChange     PlaybackEventEventType = "quality_change"
	RebufferEnd       PlaybackEventEventType = "rebuffer_end"
	RebufferStart     PlaybackEventEventType = "rebuffer_start"
	SegmentDownloaded PlaybackEventEventType = "segment_downloaded"
)

// Defines values for TranscodeJobStatus.
const (
	TranscodeJobStatusCompleted TranscodeJobStatus = "completed"
	TranscodeJobStatusFailed    TranscodeJobStatus = "failed"
	TranscodeJobStatusQueued    TranscodeJobStatus = "queued"
	TranscodeJobStatusRunning   TranscodeJobStatus = "running"
)

// Defines values for VideoStatus.
const (
	VideoStatusFailed     VideoStatus = "failed"
	VideoStatusProcessing VideoStatus = "processing"
	VideoStatusReady      VideoStatus = "ready"
	VideoStatusUploading  VideoStatus = "uploading"
)

// Defines values for VideoVisibility.
const (
	VideoVisibilityPrivate  VideoVisibility = "private"
	VideoVisibilityPublic   VideoVisibility = "public"
	VideoVisibilityUnlisted VideoVisibility = "unlisted"
)

// Defines values for UpdateVideoJSONBodyVisibility.
const (
	UpdateVideoJSONBodyVisibilityPrivate  UpdateVideoJSONBodyVisibility = "private"
	UpdateVideoJSONBodyVisibilityPublic   UpdateVideoJSONBodyVisibility = "public"
	UpdateVideoJSONBodyVisibilityUnlisted UpdateVideoJSONBodyVisibility = "unlisted"
)

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"created_at"`
	Id          string    `json:"id"`
	StreamId    string    `json:"stream_id"`
	UserId      string    `json:"user_id"`
	UserName    string    `json:"user_name"`
	UserPicture *string   `json:"user_picture,omitempty"`
}

// Comment defines model for Comment.
type Comment struct {
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"created_at"`
	Id          string    `json:"id"`
	UserId      string    `json:"user_id"`
	UserName    string    `json:"user_name"`
	UserPicture *string   `json:"user_picture,omitempty"`
	VideoId     string    `json:"video_id"`
}

// Error defines model for Error.
type Error struct {
	Code  *string `json:"code,omitempty"`
	Error string  `json:"error"`
}

// LiveStream defines model for LiveStream.
type LiveStream struct {
	CreatedAt    time.Time        `json:"created_at"`
	EndedAt      *time.Time       `json:"ended_at,omitempty"`
	HlsPath      *string          `json:"hls_path,omitempty"`
	Id           string           `json:"id"`
	RecordVod    bool             `json:"record_vod"`
	SourceCodec  *string          `json:"source_codec,omitempty"`
	SourceFps    *string          `json:"source_fps,omitempty"`
	SourceHeight *int             `json:"source_height,omitempty"`
	SourceWidth  *int             `json:"source_width,omitempty"`
	StartedAt    *time.Time       `json:"started_at,omitempty"`
	Status       LiveStreamStatus `json:"status"`
	StreamKeyId  string           `json:"stream_key_id"`
	Title        string           `json:"title"`
	UserId       string           `json:"user_id"`
	VideoId      *string          `json:"video_id,omitempty"`
}

// LiveStreamStatus defines model for LiveStream.Status.
type LiveStreamStatus string

// PlaybackEvent defines model for PlaybackEvent.
type PlaybackEvent struct {
	BufferLength       *float32               `json:"buffer_length,omitempty"`
	CurrentQuality     *string                `json:"current_quality,omitempty"`
	DownloadTimeMs     *int                   `json:"download_time_ms,omitempty"`
	ErrorCode          *string                `json:"error_code,omitempty"`
	ErrorMessage       *string                `json:"error_message,omitempty"`
	EventType          PlaybackEventEventType `json:"event_type"`
	PlaybackPosition   *float32               `json:"playback_position,omitempty"`
	QualityFrom        *string                `json:"quality_from,omitempty"`
	QualityTo          *string                `json:"quality_to,omitempty"`
	RebufferDurationMs *int                   `json:"rebuffer_duration_ms,omitempty"`
	SegmentBytes       *int64                 `json:"segment_bytes,omitempty"`
	SegmentNumber      *int                   `json:"segment_number,omitempty"`
	SegmentQuality     *string                `json:"segment_quality,omitempty"`
	ThroughputBps      *int64                 `json:"throughput_bps,omitempty"`
	Timestamp          *time.Time             `json:"timestamp,omitempty"`
}

// PlaybackEventEventType defines model for PlaybackEvent.EventType.
type PlaybackEventEventType string

// PlaybackSession defines model for PlaybackSession.
type PlaybackSession struct {
	ManifestUrl  string  `json:"manifest_url"`
	SessionId    string  `json:"session_id"`
	TelemetryUrl *string `json:"telemetry_url,omitempty"`
	Token        string  `json:"token"`
}

// StreamKey defines model for StreamKey.
type StreamKey struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	IsActive  bool      `json:"is_active"`
	RecordVod bool      `json:"record_vod"`
	UserLabel string    `json:"user_label"`
}

// TranscodeJob defines model for TranscodeJob.
type TranscodeJob struct {
	CreatedAt time.Time          `json:"created_at"`
	Error     *string            `json:"error,omitempty"`
	Id        string             `json:"id"`
	Progress  float32            `json:"progress"`
	Stage     *string            `json:"stage,omitempty"`
	Status    TranscodeJobStatus `json:"status"`
	UpdatedAt time.Time          `json:"updated_at"`
	VideoId   string             `json:"video_id"`
}

// TranscodeJobStatus defines model for TranscodeJob.Status.
type TranscodeJobStatus string

// UploadInitRequest defines model for UploadInitRequest.
type UploadInitRequest struct {
	FileSize    int64  `json:"file_size"`
	Title       string `json:"title"`
	TotalChunks int    `json:"total_chunks"`
}

// UploadInitResponse defines model for UploadInitResponse.
type UploadInitResponse struct {
	TotalChunks int    `json:"total_chunks"`
	UploadId    string `json:"upload_id"`
}

// UploadProgress defines model for UploadProgress.
type UploadProgress struct {
	Received int `json:"received"`
	Total    int `json:"total"`
}

// User defines model for User.
type User struct {
	CreatedAt        time.Time `json:"created_at"`
	Email            string    `json:"email"`
	Id               string    `json:"id"`
	Name             *string   `json:"name,omitempty"`
	Picture          *string   `json:"picture,omitempty"`
	UploadQuotaBytes int64     `json:"upload_quota_bytes"`
	UsedBytes        int64     `json:"used_bytes"`
}

// Video defines model for Video.
type Video struct {
	Codec           *string         `json:"codec,omitempty"`
	CreatedAt       time.Time       `json:"created_at"`
	Duration        *string         `json:"duration,omitempty"`
	Height          *int            `json:"height,omitempty"`
	HlsPath         *string         `json:"hls_path,omitempty"`
	Id              string          `json:"id"`
	PlayCount       int             `json:"play_count"`
	SizeBytes       *int64          `json:"size_bytes,omitempty"`
	Status          VideoStatus     `json:"status"`
	ThumbnailPath   *string         `json:"thumbnail_path,omitempty"`
	Title           string          `json:"title"`
	UpdatedAt       time.Time       `json:"updated_at"`
	UploaderName    *string         `json:"uploader_name,omitempty"`
	UploaderPicture *string         `json:"uploader_picture,omitempty"`
	UserId          *string         `json:"user_id,omitempty"`
	Visibility      VideoVisibility `json:"visibility"`
	Width           *int            `json:"width,omitempty"`
}

// VideoStatus defines model for Video.Status.
type VideoStatus string

// VideoVisibility defines model for Video.Visibility.
type VideoVisibility string

// VideoStatusResponse defines model for VideoStatus.
type VideoStatusResponse struct {
	Job   *TranscodeJob `json:"job,omitempty"`
	Video Video         `json:"video"`
}

// ListChatMessagesParams defines parameters for ListChatMessages.
type ListChatMessagesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// SendChatMessageJSONBody defines parameters for SendChatMessage.
type SendChatMessageJSONBody struct {
	Body string `json:"body"`
}

// PostTelemetryEventsJSONBody defines parameters for PostTelemetryEvents.
type PostTelemetryEventsJSONBody struct {
	Events []PlaybackEvent `json:"events"`
}

// CreateStreamKeyJSONBody defines parameters for CreateStreamKey.
type CreateStreamKeyJSONBody struct {
	Label     string `json:"label"`
	RecordVod *bool  `json:"record_vod,omitempty"`
}

// UpdateStreamKeyJSONBody defines parameters for UpdateStreamKey.
type UpdateStreamKeyJSONBody struct {
	RecordVod *bool `json:"record_vod,omitempty"`
}

// UploadThumbnailMultipartBody defines parameters for UploadThumbnail.
type UploadThumbnailMultipartBody struct {
	Thumbnail openapi_types.File `json:"thumbnail"`
}

// ListVideosParams defines parameters for ListVideos.
type ListVideosParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdateVideoJSONBody defines parameters for UpdateVideo.
type UpdateVideoJSONBody struct {
	Visibility *UpdateVideoJSONBodyVisibility `json:"visibility,omitempty"`
}

// UpdateVideoJSONBodyVisibility defines parameters for UpdateVideo.
type UpdateVideoJSONBodyVisibility string

// ListCommentsParams defines parameters for ListComments.
type ListCommentsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// AddCommentJSONBody defines parameters for AddComment.
type AddCommentJSONBody struct {
	Body string `json:"body"`
}

// SendChatMessageJSONRequestBody defines body for SendChatMessage for application/json ContentType.
type SendChatMessageJSONRequestBody SendChatMessageJSONBody

// PostTelemetryEventsJSONRequestBody defines body for PostTelemetryEvents for application/json ContentType.
type PostTelemetryEventsJSONRequestBody PostTelemetryEventsJSONBody

// CreateStreamKeyJSONRequestBody defines body for CreateStreamKey for application/json ContentType.
type CreateStreamKeyJSONRequestBody CreateStreamKeyJSONBody

// UpdateStreamKeyJSONRequestBody defines body for UpdateStreamKey for application/json ContentType.
type UpdateStreamKeyJSONRequestBody UpdateStreamKeyJSONBody

// InitUploadJSONRequestBody defines body for InitUpload for application/json ContentType.
type InitUploadJSONRequestBody = UploadInitRequest

// UploadThumbnailMultipartRequestBody defines body for UploadThumbnail for multipart/form-data ContentType.
type UploadThumbnailMultipartRequestBody UploadThumbnailMultipartBody

// UpdateVideoJSONRequestBody defines body for UpdateVideo for application/json ContentType.
type UpdateVideoJSONRequestBody UpdateVideoJSONBody

// AddCommentJSONRequestBody defines body for AddComment for application/json ContentType.
type AddCommentJSONRequestBody AddCommentJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List active live streams
	// (GET /api/v1/live)
	ListLiveStreams(w http.ResponseWriter, r *http.Request)
	// Get a live stream by ID
	// (GET /api/v1/live/{stream_id})
	GetLiveStream(w http.ResponseWriter, r *http.Request, streamId string)
	// List chat messages for a live stream
	// (GET /api/v1/live/{stream_id}/chat)
	ListChatMessages(w http.ResponseWriter, r *http.Request, streamId string, params ListChatMessagesParams)
	// Send a chat message
	// (POST /api/v1/live/{stream_id}/chat)
	SendChatMessage(w http.ResponseWriter, r *http.Request, streamId string)
	// SSE stream of live chat messages
	// (GET /api/v1/live/{stream_id}/chat/stream)
	ChatStream(w http.ResponseWriter, r *http.Request, streamId string)
	// End a live stream
	// (POST /api/v1/live/{stream_id}/end)
	EndLiveStream(w http.ResponseWriter, r *http.Request, streamId string)
	// Create a playback session for a live stream
	// (POST /api/v1/live/{stream_id}/sessions)
	CreateLiveSession(w http.ResponseWriter, r *http.Request, streamId string)
	// Get viewer count for a live stream
	// (GET /api/v1/live/{stream_id}/viewers)
	GetLiveViewers(w http.ResponseWriter, r *http.Request, streamId string)
	// Get current authenticated user
	// (GET /api/v1/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Submit batch playback telemetry events
	// (POST /api/v1/sessions/{session_id}/events)
	PostTelemetryEvents(w http.ResponseWriter, r *http.Request, sessionId string)
	// List stream keys for the current user
	// (GET /api/v1/stream-keys)
	ListStreamKeys(w http.ResponseWriter, r *http.Request)
	// Create a new stream key
	// (POST /api/v1/stream-keys)
	CreateStreamKey(w http.ResponseWriter, r *http.Request)
	// Deactivate a stream key
	// (DELETE /api/v1/stream-keys/{id})
	DeactivateStreamKey(w http.ResponseWriter, r *http.Request, id string)
	// Update a stream key
	// (PATCH /api/v1/stream-keys/{id})
	UpdateStreamKey(w http.ResponseWriter, r *http.Request, id string)
	// Initialize a chunked video upload
	// (POST /api/v1/uploads)
	InitUpload(w http.ResponseWriter, r *http.Request)
	// Upload a single chunk
	// (PUT /api/v1/uploads/{upload_id}/chunks/{chunk_number})
	ReceiveChunk(w http.ResponseWriter, r *http.Request, uploadId string, chunkNumber int)
	// Get upload progress
	// (GET /api/v1/uploads/{upload_id}/status)
	GetUploadStatus(w http.ResponseWriter, r *http.Request, uploadId string)
	// Upload a thumbnail image
	// (POST /api/v1/uploads/{upload_id}/thumbnail)
	UploadThumbnail(w http.ResponseWriter, r *http.Request, uploadId string)
	// List videos
	// (GET /api/v1/videos)
	ListVideos(w http.ResponseWriter, r *http.Request, params ListVideosParams)
	// Delete a video
	// (DELETE /api/v1/videos/{id})
	DeleteVideo(w http.ResponseWriter, r *http.Request, id string)
	// Get a video by ID
	// (GET /api/v1/videos/{id})
	GetVideo(w http.ResponseWriter, r *http.Request, id string)
	// Update video properties
	// (PATCH /api/v1/videos/{id})
	UpdateVideo(w http.ResponseWriter, r *http.Request, id string)
	// Create a playback session for a video
	// (POST /api/v1/videos/{id}/sessions)
	CreateVideoSession(w http.ResponseWriter, r *http.Request, id string)
	// Get video transcode status
	// (GET /api/v1/videos/{id}/status)
	GetVideoStatus(w http.ResponseWriter, r *http.Request, id string)
	// List comments for a video
	// (GET /api/v1/videos/{video_id}/comments)
	ListComments(w http.ResponseWriter, r *http.Request, videoId string, params ListCommentsParams)
	// Add a comment to a video
	// (POST /api/v1/videos/{video_id}/comments)
	AddComment(w http.ResponseWriter, r *http.Request, videoId string)
	// Delete a comment
	// (DELETE /api/v1/videos/{video_id}/comments/{comment_id})
	DeleteComment(w http.ResponseWriter, r *http.Request, videoId string, commentId string)
	// Log out current user
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /health/ready)
	GetHealthReady(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List active live streams
// (GET /api/v1/live)
func (_ Unimplemented) ListLiveStreams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a live stream by ID
// (GET /api/v1/live/{stream_id})
func (_ Unimplemented) GetLiveStream(w http.ResponseWriter, r *http.Request, streamId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List chat messages for a live stream
// (GET /api/v1/live/{stream_id}/chat)
func (_ Unimplemented) ListChatMessages(w http.ResponseWriter, r *http.Request, streamId string, params ListChatMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send a chat message
// (POST /api/v1/live/{stream_id}/chat)
func (_ Unimplemented) SendChatMessage(w http.ResponseWriter, r *http.Request, streamId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SSE stream of live chat messages
// (GET /api/v1/live/{stream_id}/chat/stream)
func (_ Unimplemented) ChatStream(w http.ResponseWriter, r *http.Request, streamId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// End a live stream
// (POST /api/v1/live/{stream_id}/end)
func (_ Unimplemented) EndLiveStream(w http.ResponseWriter, r *http.Request, streamId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a playback session for a live stream
// (POST /api/v1/live/{stream_id}/sessions)
func (_ Unimplemented) CreateLiveSession(w http.ResponseWriter, r *http.Request, streamId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get viewer count for a live stream
// (GET /api/v1/live/{stream_id}/viewers)
func (_ Unimplemented) GetLiveViewers(w http.ResponseWriter, r *http.Request, streamId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current authenticated user
// (GET /api/v1/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit batch playback telemetry events
// (POST /api/v1/sessions/{session_id}/events)
func (_ Unimplemented) PostTelemetryEvents(w http.ResponseWriter, r *http.Request, sessionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List stream keys for the current user
// (GET /api/v1/stream-keys)
func (_ Unimplemented) ListStreamKeys(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new stream key
// (POST /api/v1/stream-keys)
func (_ Unimplemented) CreateStreamKey(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Deactivate a stream key
// (DELETE /api/v1/stream-keys/{id})
func (_ Unimplemented) DeactivateStreamKey(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a stream key
// (PATCH /api/v1/stream-keys/{id})
func (_ Unimplemented) UpdateStreamKey(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Initialize a chunked video upload
// (POST /api/v1/uploads)
func (_ Unimplemented) InitUpload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload a single chunk
// (PUT /api/v1/uploads/{upload_id}/chunks/{chunk_number})
func (_ Unimplemented) ReceiveChunk(w http.ResponseWriter, r *http.Request, uploadId string, chunkNumber int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get upload progress
// (GET /api/v1/uploads/{upload_id}/status)
func (_ Unimplemented) GetUploadStatus(w http.ResponseWriter, r *http.Request, uploadId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload a thumbnail image
// (POST /api/v1/uploads/{upload_id}/thumbnail)
func (_ Unimplemented) UploadThumbnail(w http.ResponseWriter, r *http.Request, uploadId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List videos
// (GET /api/v1/videos)
func (_ Unimplemented) ListVideos(w http.ResponseWriter, r *http.Request, params ListVideosParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a video
// (DELETE /api/v1/videos/{id})
func (_ Unimplemented) DeleteVideo(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a video by ID
// (GET /api/v1/videos/{id})
func (_ Unimplemented) GetVideo(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update video properties
// (PATCH /api/v1/videos/{id})
func (_ Unimplemented) UpdateVideo(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a playback session for a video
// (POST /api/v1/videos/{id}/sessions)
func (_ Unimplemented) CreateVideoSession(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get video transcode status
// (GET /api/v1/videos/{id}/status)
func (_ Unimplemented) GetVideoStatus(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List comments for a video
// (GET /api/v1/videos/{video_id}/comments)
func (_ Unimplemented) ListComments(w http.ResponseWriter, r *http.Request, videoId string, params ListCommentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a comment to a video
// (POST /api/v1/videos/{video_id}/comments)
func (_ Unimplemented) AddComment(w http.ResponseWriter, r *http.Request, videoId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a comment
// (DELETE /api/v1/videos/{video_id}/comments/{comment_id})
func (_ Unimplemented) DeleteComment(w http.ResponseWriter, r *http.Request, videoId string, commentId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log out current user
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness probe
// (GET /health/ready)
func (_ Unimplemented) GetHealthReady(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListLiveStreams operation middleware
func (siw *ServerInterfaceWrapper) ListLiveStreams(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLiveStreams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetLiveStream operation middleware
func (siw *ServerInterfaceWrapper) GetLiveStream(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "stream_id" -------------
	var streamId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "stream_id", runtime.ParamLocationPath, chi.URLParam(r, "stream_id"), &streamId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stream_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveStream(w, r, streamId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListChatMessages operation middleware
func (siw *ServerInterfaceWrapper) ListChatMessages(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "stream_id" -------------
	var streamId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "stream_id", runtime.ParamLocationPath, chi.URLParam(r, "stream_id"), &streamId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stream_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListChatMessagesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChatMessages(w, r, streamId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SendChatMessage operation middleware
func (siw *ServerInterfaceWrapper) SendChatMessage(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "stream_id" -------------
	var streamId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "stream_id", runtime.ParamLocationPath, chi.URLParam(r, "stream_id"), &streamId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stream_id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendChatMessage(w, r, streamId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ChatStream operation middleware
func (siw *ServerInterfaceWrapper) ChatStream(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "stream_id" -------------
	var streamId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "stream_id", runtime.ParamLocationPath, chi.URLParam(r, "stream_id"), &streamId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stream_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChatStream(w, r, streamId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// EndLiveStream operation middleware
func (siw *ServerInterfaceWrapper) EndLiveStream(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "stream_id" -------------
	var streamId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "stream_id", runtime.ParamLocationPath, chi.URLParam(r, "stream_id"), &streamId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stream_id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EndLiveStream(w, r, streamId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateLiveSession operation middleware
func (siw *ServerInterfaceWrapper) CreateLiveSession(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "stream_id" -------------
	var streamId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "stream_id", runtime.ParamLocationPath, chi.URLParam(r, "stream_id"), &streamId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stream_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLiveSession(w, r, streamId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetLiveViewers operation middleware
func (siw *ServerInterfaceWrapper) GetLiveViewers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "stream_id" -------------
	var streamId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "stream_id", runtime.ParamLocationPath, chi.URLParam(r, "stream_id"), &streamId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stream_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveViewers(w, r, streamId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostTelemetryEvents operation middleware
func (siw *ServerInterfaceWrapper) PostTelemetryEvents(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "session_id", runtime.ParamLocationPath, chi.URLParam(r, "session_id"), &sessionId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTelemetryEvents(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListStreamKeys operation middleware
func (siw *ServerInterfaceWrapper) ListStreamKeys(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListStreamKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateStreamKey operation middleware
func (siw *ServerInterfaceWrapper) CreateStreamKey(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateStreamKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeactivateStreamKey operation middleware
func (siw *ServerInterfaceWrapper) DeactivateStreamKey(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeactivateStreamKey(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateStreamKey operation middleware
func (siw *ServerInterfaceWrapper) UpdateStreamKey(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateStreamKey(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// InitUpload operation middleware
func (siw *ServerInterfaceWrapper) InitUpload(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InitUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ReceiveChunk operation middleware
func (siw *ServerInterfaceWrapper) ReceiveChunk(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "upload_id" -------------
	var uploadId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "upload_id", runtime.ParamLocationPath, chi.URLParam(r, "upload_id"), &uploadId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "upload_id", Err: err})
		return
	}

	// ------------- Path parameter "chunk_number" -------------
	var chunkNumber int

	err = runtime.BindStyledParameterWithLocation("simple", false, "chunk_number", runtime.ParamLocationPath, chi.URLParam(r, "chunk_number"), &chunkNumber)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chunk_number", Err: err})
		return
	}

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReceiveChunk(w, r, uploadId, chunkNumber)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetUploadStatus operation middleware
func (siw *ServerInterfaceWrapper) GetUploadStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "upload_id" -------------
	var uploadId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "upload_id", runtime.ParamLocationPath, chi.URLParam(r, "upload_id"), &uploadId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "upload_id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUploadStatus(w, r, uploadId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UploadThumbnail operation middleware
func (siw *ServerInterfaceWrapper) UploadThumbnail(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "upload_id" -------------
	var uploadId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "upload_id", runtime.ParamLocationPath, chi.URLParam(r, "upload_id"), &uploadId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "upload_id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadThumbnail(w, r, uploadId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListVideos operation middleware
func (siw *ServerInterfaceWrapper) ListVideos(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVideosParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVideos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteVideo operation middleware
func (siw *ServerInterfaceWrapper) DeleteVideo(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVideo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetVideo operation middleware
func (siw *ServerInterfaceWrapper) GetVideo(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVideo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateVideo operation middleware
func (siw *ServerInterfaceWrapper) UpdateVideo(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateVideo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateVideoSession operation middleware
func (siw *ServerInterfaceWrapper) CreateVideoSession(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVideoSession(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetVideoStatus operation middleware
func (siw *ServerInterfaceWrapper) GetVideoStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVideoStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListComments operation middleware
func (siw *ServerInterfaceWrapper) ListComments(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "video_id" -------------
	var videoId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "video_id", runtime.ParamLocationPath, chi.URLParam(r, "video_id"), &videoId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "video_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCommentsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListComments(w, r, videoId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AddComment operation middleware
func (siw *ServerInterfaceWrapper) AddComment(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "video_id" -------------
	var videoId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "video_id", runtime.ParamLocationPath, chi.URLParam(r, "video_id"), &videoId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "video_id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddComment(w, r, videoId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteComment operation middleware
func (siw *ServerInterfaceWrapper) DeleteComment(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "video_id" -------------
	var videoId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "video_id", runtime.ParamLocationPath, chi.URLParam(r, "video_id"), &videoId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "video_id", Err: err})
		return
	}

	// ------------- Path parameter "comment_id" -------------
	var commentId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "comment_id", runtime.ParamLocationPath, chi.URLParam(r, "comment_id"), &commentId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "comment_id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteComment(w, r, videoId, commentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetHealthReady operation middleware
func (siw *ServerInterfaceWrapper) GetHealthReady(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/live", wrapper.ListLiveStreams)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/live/{stream_id}", wrapper.GetLiveStream)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/live/{stream_id}/chat", wrapper.ListChatMessages)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/live/{stream_id}/chat", wrapper.SendChatMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/live/{stream_id}/chat/stream", wrapper.ChatStream)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/live/{stream_id}/end", wrapper.EndLiveStream)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/live/{stream_id}/sessions", wrapper.CreateLiveSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/live/{stream_id}/viewers", wrapper.GetLiveViewers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/sessions/{session_id}/events", wrapper.PostTelemetryEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/stream-keys", wrapper.ListStreamKeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/stream-keys", wrapper.CreateStreamKey)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/stream-keys/{id}", wrapper.DeactivateStreamKey)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/stream-keys/{id}", wrapper.UpdateStreamKey)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/uploads", wrapper.InitUpload)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/uploads/{upload_id}/chunks/{chunk_number}", wrapper.ReceiveChunk)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/uploads/{upload_id}/status", wrapper.GetUploadStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/uploads/{upload_id}/thumbnail", wrapper.UploadThumbnail)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/videos", wrapper.ListVideos)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/videos/{id}", wrapper.DeleteVideo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/videos/{id}", wrapper.GetVideo)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/videos/{id}", wrapper.UpdateVideo)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/videos/{id}/sessions", wrapper.CreateVideoSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/videos/{id}/status", wrapper.GetVideoStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/videos/{video_id}/comments", wrapper.ListComments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/videos/{video_id}/comments", wrapper.AddComment)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/videos/{video_id}/comments/{comment_id}", wrapper.DeleteComment)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health/ready", wrapper.GetHealthReady)
	})

	return r
}
